#setting up iMetAMOS
install in utilities directory but running in docker

wget https://github.com/marbl/metAMOS/archive/v1.5rc3.zip
unzip v1.5rc3.zip

key error for os.environ["SHELL"] - install in utilities from desktop

Messages from running python INSTALL.py imetAMOS
To make things easier for you, you may want to copy/symlink the following
files into a directory in your PATH:
  /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/kraken/bin/kraken
  /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/kraken/bin/kraken-build
  /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/kraken/bin/kraken-filter
  /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/kraken/bin/kraken-mpa-report
  /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/kraken/bin/kraken-report
Could not import pysam, disabling.
Could not import psutil, disabling.

Kraken database download
tar (child): minikraken.tgz: Cannot open: Timer expired
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mv: cannot stat â€˜minikraken_*â€™: No such file or directory

KronaTools install error
syntax error at ./install.pl line 58, near ")"
  (Might be a runaway multi-line () string starting on line 37)
syntax error at ./install.pl line 80, near "}"
Illegal declaration of subroutine main::createDir at ./install.pl line 89.

SignalP is not installed and is required for Prokka's gram option. Please download it and add it to your path.
had to download from DTU website using UMD email address

no error when rerunning the install script

error with Ray not MPI

Issues with minikraken database - tried downloading multiple times and still received an error regarding opening the database.

Running tests
run_pipeline_test.sh - issue with Krona tools
run_test2.sh issue with nb_classify
run_test_fast.sh - error cannot locate KronaTools.pm
run_test_amphora.sh - error with KronaTools when calling ImportPhylosift 


Error with syntax error: bad fd number 
/bin/sh link to dash changed to bash following recomendations on 
http://stackoverflow.com/questions/15809060/sh-syntax-error-bad-fd-number
```sudo mv /bin/sh /bin/sh.orig
sudo ln -s /bin/bash /bin/sh```

issue with KronaTools install - manually added links to perl scripts KronaTools directory between scirpts and bin

for error with fcb_models
downloaded from metamos cbcb ftp site extracted on laptop and used rsync to transfer to desktop into metaAMOS utilities/models directory

found potential bug in the KronaTools install script

for Ray install added MPI to path 
	sudo apt-get install libopenmpi-dev
	reran pyhton INSTALL.py imetAMOS 
	able to install Ray!
after fixing bug with krona perl script able to run run_pipeline_test.sh

FRCbam install error related to boost
apt-get install libboost-system-dev libboost-isostreams-dev
still not able to install

installing CA - gmake not 
running test_ima.sh - 


### imetAMOS run
error with SRR1555300
*****************************************************************
*************************ERROR***********************************
During findorfs, the following command failed with return code 2:
>> /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/prokka/bin/prokka  --outdir /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structurm: cannot remove â€˜/media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Logs/findorfs.okâ€™: No such file or directory
Traceback (most recent call last):
  File "./runPipeline", line 984, in <module>
    verbose = 1)
  File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 2965, in pipeline_run
    raise job_errors
RethrownJobError: 
    
    
    
    Exception #1
      'exceptions.TypeError(exceptions must be old-style classes or derived from BaseException, not NoneType)' raised in ...
       Task = def validate.Validate(...):
       Job  = [[abyss.91.faa, idba-ud.91.faa, masurca.91.faa, sga.91.faa, soapdenovo2.91.faa, spades.91.faa, velvet.91.faa] -> [validate.ok]]
    
    Traceback (most recent call last):
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 625, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 491, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/validate.py", line 690, in Validate
        FindORFS("%s/Assemble/out/%s.contig.cvg"%(_settings.rundir, _settings.PREFIX), "%s/Assemble/out/%s.faa"%(_settings.rundir, _settings.PREFIX))
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/findorfs.py", line 380, in FindORFS
        findFastaORFs(_orf, "%s/FindORFS/in/%s.asm.contig"%(_settings.rundir, _settings.PREFIX), "%s.ctg.fna"%(_settings.PREFIX), "%s.ctg.faa"%(_settings.PREFIX), "%s.ctg.gene.cvg"%(_settings.PREFIX), "%s.ctg.gene.map"%(_settings.PREFIX), _min_ctg_len, _min_ctg_cvg)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/findorfs.py", line 337, in findFastaORFs
        run_process(_settings, "%s/prokka %s --outdir %s/FindORFS/out/%s.prokka --prefix %s --force %s"%(_settings.PROKKA,"--fast" if _run_fast else "",  _settings.rundir, _settings.PREFIX, _settings.PREFIX, contigs), "FindORFS")
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/utils.py", line 1145, in run_process
        raise
    TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
    
    
re/SRR155300/FindORFS/out/proba.prokka --prefix proba --force /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/FindORFS/in/proba.asm.contig

*************************DETAILS***********************************
Last 10 commands run before the error (/media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Logs/COMMANDS.log)
|2014-11-25 05:44:09| ln /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/.asm.tigr /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/proba.asm.tigr
|2014-11-25 05:44:09| unlink /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/proba.contig.cnt
|2014-11-25 05:44:09| ln /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/.contig.cnt /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/proba.contig.cnt
|2014-11-25 05:44:09| unlink /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/proba.contig.cvg
|2014-11-25 05:44:09| ln /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/.contig.cvg /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/proba.contig.cvg
|2014-11-25 05:44:09| unlink /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/proba.afg
|2014-11-25 05:44:09| rm /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Logs/findorfs.ok
|2014-11-25 05:44:09| unlink /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/FindORFS/in/proba.asm.contig
|2014-11-25 05:44:09| ln /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Assemble/out/proba.asm.contig /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/FindORFS/in/proba.asm.contig
|2014-11-25 05:44:11| /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/prokka/bin/prokka  --outdir /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/FindORFS/out/proba.prokka --prefix proba --force /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/FindORFS/in/proba.asm.contig

Last 10 lines of output (/media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/Logs/FINDORFS.log)
[05:44:10] Determined parallel version is 20130822
[05:44:10] Looking for 'prodigal' - found /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/prokka/bin/../binaries/linux/prodigal
[05:44:10] Determined prodigal version is 2.60
[05:44:10] Looking for 'sed' - found /bin/sed
[05:44:10] Looking for 'signalp' - found /usr/local/bin/signalp
[05:44:11] Determined signalp version is 4.1
[05:44:11] Looking for 'tbl2asn' - found /usr/local/bin/tbl2asn
[05:44:11] Determined tbl2asn version is 23.9
[05:44:11] Using genetic code table 11.
[05:44:11] '/media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR155300/FindORFS/in/proba.asm.contig' is not a readable non-empty FASTA file

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
*************************ERROR***********************************
*****************************************************************[0m
Oops, MetAMOS finished with errors! see text in red above for details.

## Error with SRR1555298 run 
*** metAMOS running command: head -n 4 /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555298/Preprocess/out/lib1.fasta > /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_struTraceback (most recent call last):
  File "./runPipeline", line 984, in <module>
    verbose = 1)
  File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 2965, in pipeline_run
    raise job_errors
RethrownJobError: 
    
    
    
    Exception #1
      'exceptions.ValueError(invalid literal for int() with base 10: '42\n42')' raised in ...
       Task = def assemble.Assemble(...):
       Job  = [idba-ud.67.run -> idba-ud.67.asm.contig]
    
    Traceback (most recent call last):
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 625, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 491, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/assemble.py", line 537, in Assemble
        generic.execute(STEP_NAMES.ASSEMBLE, asmName.lower(), _settings)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/generic.py", line 493, in execute
        return dispatch.execute()
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/generic.py", line 342, in execute
        (havePE, haveMP, offset, input, pelist, mplist, techParams) = self.getLibInput()
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/generic.py", line 251, in getLibInput
        if (int(libReadLen) < self.readLen):
    ValueError: invalid literal for int() with base 10: '42\n42'
    
    
cture/SRR1555298/Preprocess/out/tmp.fasta

*** metAMOS running command: rm -f /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555298/Preprocess/out/tmp.fasta

Oops, MetAMOS finished with errors! see text in red above for details.

## Restarted SRR1555300 run from terminal
11/25/2014 


Trying to Run using the binary
nolson@Selenium:/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS_v1.5rc2_binary$ ./initPipeline -q -1 ../../data/RM8375/MiSeq/fastq/SRR1555298_1.fastq -2 ../../data/RM8375/MiSeq/fastq/SRR1555298_2.fastq  -d ../../analysis/bioinf/genome_structure/SRR1555298-b -i 500:700 -W iMetAMOS
Error: cannot find BLAST DB directory, yet path set via $BLASTDB: /var/lib/blastdb. Disabling blastdb dependent programs
Project dir /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555298-b successfully created!
Use runPipeline.py to start Pipeline
nolson@Selenium:/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS_v1.5rc2_binary$ ./runPipeline -v -d ../../analysis/bioinf/
genome_purity/        genome_structure/     get_fastq/            sequence_homogeneity/ sequence_purity/      
nolson@Selenium:/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS_v1.5rc2_binary$ ./runPipeline -v -d ../../analysis/bioinf/genome_structure/SRR1555298-b/
Warning: Cannot determine OS, defaulting to Linux
Warning: Cannot determine OS version, defaulting to 0.0
Warning: Cannot determine system type, defaulting to x86_64
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.11' not found (required by sh)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.14' not found (required by sh)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.8' not found (required by sh)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.15' not found (required by sh)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.14' not found (required by /lib/x86_64-linux-gnu/libtinfo.so.5)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.15' not found (required by /lib/x86_64-linux-gnu/libtinfo.so.5)
Error: cannot find BLAST DB directory, yet path set via $BLASTDB: /var/lib/blastdb. Disabling blastdb dependent programs
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.11' not found (required by sh)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.14' not found (required by sh)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.8' not found (required by sh)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.15' not found (required by sh)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.14' not found (required by /lib/x86_64-linux-gnu/libtinfo.so.5)
sh: /tmp/_MEIutl4pm/lib/libc.so.6: version `GLIBC_2.15' not found (required by /lib/x86_64-linux-gnu/libtinfo.so.5)
IOError: [Errno 2] No such file or directory: '/tmp/_MEIutl4pm/phylosift/phylosiftrc.orig'

restarted ./runPipeline for SRR1555298 with -f assembly got the following error
*** metAMOS running command: /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/prokka/bin/prokka  --outdir /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/FindORFS/out/proba.prokka --prefix proba --force /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/FindORFS/in/proba.asm.contig

[*****************************************************************
*************************ERROR***********************************
During findorfs, the following command failed with return code 2:
>> /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/prokka/bin/prokka  --outdir /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/FindORFS/out/proba.prokka --prefix proba --force /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/FindORFS/in/proba.asm.contig

*************************DETAILS***********************************
Last 10 commands run before the error (/media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Logs/COMMANDS.log)
|2014-11-25 15:05:12| ln /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/.asm.tigr /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/proba.asm.tigr
|2014-11-25 15:05:12| unlink /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/proba.contig.cnt
|2014-11-25 15:05:12| ln /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/.contig.cnt /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/proba.contig.cnt
|2014-11-25 15:05:12| unlink /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/proba.contig.cvg
|2014-11-25 15:05:12| ln /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/.contig.cvg /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/proba.contig.cvg
|2014-11-25 15:05:12| unlink /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/proba.afg
|2014-11-25 15:05:12| rm /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Logs/findorfs.ok
|2014-11-25 15:05:12| unlink /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/FindORFS/in/proba.asm.contig
|2014-11-25 15:05:12| ln /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Assemble/out/proba.asm.contig /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/FindORFS/in/proba.asm.contig
|2014-11-25 15:05:13| /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/prokka/bin/prokka  --outdir /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/FindORFS/out/proba.prokka --prefix proba --force /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/FindORFS/in/proba.asm.contig

Last 10 lines of output (/media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Logs/FINDORFS.log)
[15:05:13] Determined parallel version is 20130822
[15:05:13] Looking for 'prodigal' - found /media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/prokka/bin/../binaries/linux/prodigal
[15:05:13] Determined prodigal version is 2.60
[15:05:13] Looking for 'sed' - found /bin/sed
[15:05:13] Looking for 'signalp' - found /usr/local/bin/signalp
[15:05:13] Determined signalp version is 4.1
[15:05:13] Looking for 'tbl2asn' - found /usr/local/bin/tbl2asn
[15:05:13] Determined tbl2asn version is 23.9
[15:05:13] Using genetic code table 11.
[15:05:13] '/media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/FindORFS/in/proba.asm.contig' is not a readable non-empty FASTA file

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
*************************ERROR***********************************
*****************************************************************
rm: cannot remove â€˜/media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555300/Logs/findorfs.okâ€™: No such file or directory
Oops, MetAMOS finished with errors! see text in red above for details.
Traceback (most recent call last):
  File "./runPipeline", line 984, in <module>
    verbose = 1)
  File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 2965, in pipeline_run
    raise job_errors
RethrownJobError: 
    
    
    
    Exception #1
      'exceptions.TypeError(exceptions must be old-style classes or derived from BaseException, not NoneType)' raised in ...
       Task = def validate.Validate(...):
       Job  = [[abyss.91.faa, idba-ud.91.faa, masurca.91.faa, sga.91.faa, soapdenovo2.91.faa, spades.91.faa, velvet.91.faa] -> [validate.ok]]
    
    Traceback (most recent call last):
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 625, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 491, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/validate.py", line 690, in Validate
        FindORFS("%s/Assemble/out/%s.contig.cvg"%(_settings.rundir, _settings.PREFIX), "%s/Assemble/out/%s.faa"%(_settings.rundir, _settings.PREFIX))
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/findorfs.py", line 380, in FindORFS
        findFastaORFs(_orf, "%s/FindORFS/in/%s.asm.contig"%(_settings.rundir, _settings.PREFIX), "%s.ctg.fna"%(_settings.PREFIX), "%s.ctg.faa"%(_settings.PREFIX), "%s.ctg.gene.cvg"%(_settings.PREFIX), "%s.ctg.gene.map"%(_settings.PREFIX), _min_ctg_len, _min_ctg_cvg)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/findorfs.py", line 337, in findFastaORFs
        run_process(_settings, "%s/prokka %s --outdir %s/FindORFS/out/%s.prokka --prefix %s --force %s"%(_settings.PROKKA,"--fast" if _run_fast else "",  _settings.rundir, _settings.PREFIX, _settings.PREFIX, contigs), "FindORFS")
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/utils.py", line 1145, in run_process
        raise
    TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

### Removed SRR1555298 and SRR1555300 directories 
new initPipeline and run for SRR1555298
nolson@Selenium:/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3$ ./initPipeline -q -1 ../../data/RM8375/MiSeq/fastq/SRR1555298_1.fastq  -2 ../../data/RM8375/MiSeq/fastq/SRR1555298_2.fastq -i 500:1000 -W imetAMOS -d ../../analysis/bioinf/genome_structure/SRR1555298
Project dir /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555298 successfully created!
Use runPipeline.py to start Pipeline

*** metAMOS running command: rm -f /media/nolson/second/current_projects/micro_rm_dev/analysis/bioinf/genome_structure/SRR1555298/Preprocess/out/tmp.fasta

Oops, MetAMOS finished with errors! see text in red above for details.
Traceback (most recent call last):
  File "./runPipeline", line 984, in <module>
    verbose = 1)
  File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 2965, in pipeline_run
    raise job_errors
RethrownJobError: 
    
    
    
    Exception #1
      'exceptions.ValueError(invalid literal for int() with base 10: '42\n42')' raised in ...
       Task = def assemble.Assemble(...):
       Job  = [idba-ud.67.run -> idba-ud.67.asm.contig]
    
    Traceback (most recent call last):
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 625, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 491, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/assemble.py", line 537, in Assemble
        generic.execute(STEP_NAMES.ASSEMBLE, asmName.lower(), _settings)
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/generic.py", line 493, in execute
        return dispatch.execute()
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/generic.py", line 342, in execute
        (havePE, haveMP, offset, input, pelist, mplist, techParams) = self.getLibInput()
      File "/media/nolson/second/current_projects/micro_rm_dev/utilities/metAMOS-1.5rc3/src/generic.py", line 251, in getLibInput
        if (int(libReadLen) < self.readLen):
    ValueError: invalid literal for int() with base 10: '42\n42'
Errors could be due to memory usage by pathoreport

Restarted after with pathoreport not running, same error, trying another dataset.
Potential issue with inaccurate estimate in insert size or bug in code ...

Ran SRR1555302
./initPipeline -q -1 ../../data/RM8375/MiSeq/fastq/SRR1555302_1.fastq -2 ../../data/RM8375/MiSeq/fastq/SRR1555302_2.fastq -i 500:700 -W imetAMOS -d ../../analysis/bioinf/genome_structure/SRR1555302
./runPipeline -v -d ../../analysis/bioinf/genome_structure/SRR1555302/
Started run SRR1555304
./initPipeline -q -1 ../../data/RM8375/MiSeq/fastq/SRR1555304_1.fastq -2 ../../data/RM8375/MiSeq/fastq/SRR1555304_2.fastq -i 500:700 -W imetAMOS -d ../../analysis/bioinf/genome_structure/SRR1555304
./runPipeline -v -d ../../analysis/bioinf/genome_structure/SRR1555304/